### ISSUE TITLE
Can you help me configure?

### ISSUE THREAD

**Issue by Barabba11** [namgk/node-red-contrib-firebase-messaging#7]
Hi mate, sorry I'm a beginner with Google firebase, I just know I want to push out values from NR and see a chart in Google, I hope your node can helo me doing that.
Can you kindly write a small guide? For example:
- Go to https://firebase.google.com/ do something there and obtain the .json file
- copy the json into Rasberry and let the module find the file
- Push data to google in this way
- on https://firebase.google.com/ click on charts and see your chart.

Thank you for helping me!

**Comment by Barabba11** [comment]
I've created a project and got the json file, I've pasted it int your node. Then what I suppose to do? How can I push data, with with object? In which structure? Really a pity there isn't an example in your project (

**Comment by namgk** [comment]
You should be familiar with Firebase Messaging in order to use this node. For example, with "notification" type of push, you need to send a payload with a body and a title properties to the node.

![image](https://user-images.githubusercontent.com/1003424/132050554-c2186bc2-d42d-43d2-bb9a-36cd2d98dcb0.png)

Actually much of the use case you can find in test cases. You'll know what payload format the node accepts.

**Comment by namgk** [comment]
If you want to send a message to a single device, you should configure the node to be of type "Data" and inject to the node the following msg format:

```json
{
   "payload": "<any object data>",
   "token": "<fcm token>"
}
```

**Comment by namgk** [comment]
Also it seems you're using a wrong node, this node is for FCM Messaging, i.e. push notification for mobile devices using Firebase's messaging service.

**Comment by Barabba11** [comment]
Thank you for your kind support,
my goal is to push to Google the data of the sensor and build a chart about them. If I push to google data I don't have to create a local database and manage data inside, I suppose I can just push X:Y (time:data) and itself will create chart from that. Is it possible?
No I'm not familiar, if it is too complicated I'll avoid to continue. Thnak you

**Comment by namgk** [comment]
I think you're at the wrong place. Have a look at influxdb or ubidots if
you want to work on sensor data.

**Comment by Barabba11** [comment]
thank you, you opened my eyes, I had a look to influxdb and seems free of charge, there is a Nodered module and also arduino library. I can put some efforts to know how it works and use them for different systems later.
I didn't see ubidots, which is the more simple to push data and see chart? Thank you!

**Comment by namgk** [comment]
you're welcome
